# Generated by Django 4.1.4 on 2023-01-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_complete',
            field=models.TextField(),
        ),
    ]
