# Generated by Django 4.1.5 on 2023-01-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='note',
        ),
    ]
